$("#b1").click(function(){
  $(this).toggleClass("changeColor");
  $("#b2").removeClass("changeColor");
  $("#b3").removeClass("changeColor");
});
$("#b2").click(function(){
  $(this).toggleClass("changeColor");
  $("#b1").removeClass("changeColor");
  $("#b3").removeClass("changeColor");
});
$("#b3").click(function(){
  $(this).toggleClass("changeColor");
  $("#b1").removeClass("changeColor");
  $("#b2").removeClass("changeColor");
});
